In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ca_df = pd.read_excel(
    io="CTIA-01.02-Operator-Priority-List-V4.0.1.xlsx",
    sheet_name="NonEssential High Priority",
    usecols="B,D:F",
    skiprows=[0, 1, 2, 3, 67, 68, 69, 70, 71],
)
tis_ca_df = ca_df.iloc[0:22]
trp_ca_df = ca_df.iloc[34:65]
att_vals = list(tis_ca_df["AT&T"].dropna().values.astype(str))
for i in range(len(att_vals)):
    att_vals[i] = att_vals[i][
        : att_vals[i].find("A", len(att_vals[i]) - 4, len(att_vals[i])) + 1
    ]
    if "_" in att_vals[i]:
        att_vals[i] = att_vals[i].replace("_", "-")
    if "or" in att_vals[i]:
        att_vals.append(att_vals[i].split(" or ")[1])
        att_vals[i] = att_vals[i].split(" or ")[0]
        att_vals[i] = att_vals[i][
            : att_vals[i].find("A", len(att_vals[i]) - 4, len(att_vals[i])) + 1
        ]

att_vals
# trp_ca_df

['2A-14A',
 '2A-12A',
 '2A-29A',
 '2A-30A',
 '2A-12A-30A',
 '2A-29A-30A',
 '2A-4A-12A',
 '2A-4A-5A',
 '2A-12A-66A',
 '2A-5A-66A']

In [10]:
tis_ca_df = tis_ca_df.apply(lambda x: x.replace("_", "-"))
# tis_ca_df["AT&T"].dropna().apply(lambda x: x.replace("_", "-"))
tis_ca_df

,AT&T,T-Mobile,Verizon,US Cellular
0,"2A_14A2,6",66A-12A2,"13A-4A2,3 or 13A-66A2,3",2A-12A2
1,2A-12A2,66A-2A2,"2A-4A2,3 or 2A-66A2,3",2A-5A2
2,2A-29A2,66A-66A2,13A-2A2,66A-12A
3,2A-30A2,66C,2A-5A2,66A-5A
4,2A-12A-30A,2A-12A-66A5,13A-48A2,66A-2A
5,2A-29A-30A,66A-2A-12A5,66A-48A2,2A-5A-66A
6,"2A-4A-12A3,5 or 2A-12A-66A3,5",12A-2A-66A4,13A-2A-4A3 or 13A-2A-66A3,2A-12A-66A5
7,2A-4A-5A3 or 2A-5A-66A3,66A-12A-66A5,2A-4A-5A3 or 2A-5A-66A3,NaN
8,NaN,12A-66A-66A4,13A-48A-66A,NaN
9,NaN,2A-66A-66A5,66A-2A-48A,NaN
10,NaN,66A-2A-66A4,NaN,NaN
11,NaN,2A-2A-66A4,NaN,NaN
12,NaN,66A-2A-2A5,NaN,NaN
13,NaN,2A-2A-12A4,NaN,NaN
14,NaN,12A-2A-2A5,NaN,NaN
15,NaN,25A-26A,NaN,NaN
16,NaN,41A-41A,NaN,NaN
17,NaN,41C,NaN,NaN
18,NaN,2A-66C,NaN,NaN
19,NaN,25A-25A,NaN,NaN
20,NaN,12A-2A2,NaN,NaN
21,NaN,2A-12A2,NaN,NaN

In [20]:
bands = tis_ca_df.to_dict("list")
bands

{'AT&T': ['2A_14A2,6',
  '2A-12A2',
  '2A-29A2',
  '2A-30A2',
  '2A-12A-30A',
  '2A-29A-30A',
  '2A-4A-12A3,5 or 2A-12A-66A3,5',
  '2A-4A-5A3 or 2A-5A-66A3',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'T-Mobile': ['66A-12A2',
  '66A-2A2',
  '66A-66A2',
  '66C',
  '2A-12A-66A5',
  '66A-2A-12A5',
  '12A-2A-66A4',
  '66A-12A-66A5',
  '12A-66A-66A4',
  '2A-66A-66A5',
  '66A-2A-66A4',
  '2A-2A-66A4',
  '66A-2A-2A5',
  '2A-2A-12A4',
  '12A-2A-2A5',
  '25A-26A',
  '41A-41A',
  '41C',
  '2A-66C',
  '25A-25A',
  '12A-2A2',
  '2A-12A2'],
 'Verizon': ['13A-4A2,3 or 13A-66A2,3',
  '2A-4A2,3 or 2A-66A2,3',
  '13A-2A2',
  '2A-5A2',
  '13A-48A2',
  '66A-48A2',
  '13A-2A-4A3 or 13A-2A-66A3',
  '2A-4A-5A3 or 2A-5A-66A3',
  '13A-48A-66A',
  '66A-2A-48A',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan],
 'US Cellular': ['2A-12A2',
  '2A-5A2',
  '66A-12A',
  '66A-5A',
  '66A-2A',
  '2A-5A-66A',
  '2A-12A-66A5',
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan,
  nan]}

In [51]:
from quectel_bands import QuectelBands

q = QuectelBands()
rmbands = q.ca_combos["RM500Q-GL"]
bands = rmbands.iloc[1:]
bands.dropna(how="all", inplace=True)
rm500_bands = bands.dropna(how="all").to_dict("list")
for val in range(len(rm500_bands["RM500Q-GL    2CA"])):
    if type(rm500_bands["RM500Q-GL    2CA"][val]) != float:
        if "CA_" in rm500_bands["RM500Q-GL    2CA"][val]:
            rm500_bands["RM500Q-GL    2CA"][val] = rm500_bands["RM500Q-GL    2CA"][
                val
            ].lstrip("CA_")
    else:
        continue
rmbands.keys()

C:\Users\16062\AppData\Local\Temp\ipykernel_2208\1862166677.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bands.dropna(how="all", inplace=True)

Index(['RM500Q-GL    2CA', 'RM500Q-GL    3CA',
       'RM500Q-GL   EN-DC (1LTE + 1NR)', 'RM500Q-GL   EN-DC (2LTE + 1NR)',
       'RM500Q-GL   EN-DC  (3LTE + 1NR)'],
      dtype='object')

In [6]:
from operator_bands import OperatorBandsNR

df = OperatorBandsNR().nr_df
tis_df = df.iloc[0:17]
tis_df
trp_df = df.iloc[34:60]
trp_df

,AT&T.1,T-Mobile.1,Verizon4,US Cellular.1
34,DC_2A-n5A,DC_2A_n41A2,DC_2A_n5A,DC_2A_n71A
35,DC_2A_n30A2,DC_66A_n41A2,DC_13A_n2A1,DC_66A_n71A
36,DC_5A-n2A2,DC_2A_n71A,DC_13A_n5A2,"DC_2A_n77A1,2"
37,DC_5A_n30A2,DC_66A_n71A,DC_13A_n66A,"DC_66A_n77A1,2"
38,DC_12A_n2A2,DC_2A_66A_n71A2,DC_48A_n5A2,NaN
39,DC_12A_n30A2,DC_2A_66A_n25A2,DC_2A_n77A2,NaN
40,DC_12A_n77A2,DC_2A_2A_n71A2,DC_13A_n77A2,NaN
41,DC_14A_n30A2,DC_2A_n66A,"DC_66A_n77A1,2",NaN
42,DC_30A_n2A2,DC_66A_n258A,DL DC_13A-66A_n2A with UL DC_13A_n2A2,NaN
43,DC_30A_n5A2,DC_66A_n260A,DL DC_2A-66A_n5A with UL DC_66A_n5A2,NaN
44,DC_30A_n66A2,NaN,DL DC_2A-13A-66A_n77A with UL DC_66A_n77A2,NaN
45,DC_66A_n30A2,NaN,DC_66A_n260A,NaN
46,DC_2A-66A_n5A2,NaN,DC_66A_n261A,NaN
47,DC_2A-12A_n30A2,NaN,NaN,NaN
48,DC_2A-14A_n66A2,NaN,NaN,NaN
49,DC_12A-66A_n77A2,NaN,NaN,NaN
50,DC_14A-66A_n2A2,NaN,NaN,NaN
51,DC_2A-14A-66A_n2A2,NaN,NaN,NaN
52,DC_2A-14A-66A_n66A2,NaN,NaN,NaN
53,DC_12A-14A-30A_n77A2,NaN,NaN,NaN
54,DC_2A-12A-30A-66A_n77A2,NaN,NaN,NaN
55,DC_2A-14A-66A-66A_n2A2,NaN,NaN,NaN
56,DC_66A_n260A,NaN,NaN,NaN
57,NaN,NaN,NaN,NaN
58,NaN,NaN,NaN,NaN
59,NaN,NaN,NaN,NaN